# Generated by Django 3.2.6 on 2021-08-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0003_cundercomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cundercomment',
            name='comment_content',
            field=models.TextField(blank=True),
        ),
    ]
