# Generated by Django 3.2.6 on 2021-08-19 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0004_cundercomment_comment_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cquestion',
            name='away_university',
        ),
        migrations.RemoveField(
            model_name='cquestion',
            name='home_university',
        ),
    ]
