# Generated by Django 3.2.6 on 2021-09-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0004_cundercomment_comment_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cquestion',
            name='away_university',
        ),
        migrations.RemoveField(
            model_name='cquestion',
            name='home_university',
        ),
        migrations.AddField(
            model_name='cquestion',
            name='hits',
            field=models.PositiveIntegerField(default=0, verbose_name='조회수'),
        ),
    ]
