# Generated by Django 3.2.6 on 2021-08-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domestic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_name', models.CharField(max_length=50)),
                ('home_apply', models.TextField(blank=True)),
                ('home_document', models.TextField(blank=True)),
                ('semester', models.TextField(blank=True)),
                ('home_scholarship', models.TextField(blank=True)),
                ('insurance', models.TextField(blank=True)),
            ],
        ),
    ]
