# Generated by Django 3.2.6 on 2021-08-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(max_length=20)),
                ('credit', models.IntegerField(default=1)),
                ('grade_average', models.FloatField(default=0.0)),
                ('apply_semester', models.CharField(choices=[('1학기', '1학기'), ('2학기', '2학기')], max_length=20)),
                ('pass_fail', models.CharField(choices=[('O', 'O'), ('X', 'X')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.TextField(null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Domestic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_name', models.CharField(max_length=50)),
                ('home_apply', models.TextField(blank=True)),
                ('home_document', models.TextField(blank=True)),
                ('semester', models.TextField(blank=True)),
                ('home_scholarship', models.TextField(blank=True)),
                ('insurance', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(max_length=50)),
                ('question_content', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
