# Generated by Django 3.2.6 on 2021-08-10 02:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='credit',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AlterField(
            model_name='credit',
            name='grade_average',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4.5)]),
        ),
    ]
