# Generated by Django 3.2.6 on 2021-08-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foreign', '0002_initial'),
        ('domestic', '0002_domestic_home_sister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domestic',
            name='home_sister',
            field=models.ManyToManyField(blank=True, null=True, related_name='sisters', to='foreign.Foreign', verbose_name='자매결연'),
        ),
    ]
