# Generated by Django 3.2.6 on 2021-08-08 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foreign', '0003_post_foreign'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('domestic', '0003_dcomment_dquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.IntegerField(default=1)),
                ('apply_semester', models.CharField(choices=[('1학기', '1학기'), ('2학기', '2학기')], max_length=20)),
                ('pass_fail', models.BooleanField(default=0)),
                ('away_university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foreign.foreign')),
                ('credit_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('home_school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='domestic.domestic')),
            ],
        ),
    ]
