# Generated by Django 3.2.6 on 2021-08-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic', '0004_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='college',
            field=models.CharField(default='인문대', max_length=20),
            preserve_default=False,
        ),
    ]
