# Generated by Django 3.2.6 on 2021-08-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic', '0005_credit_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='grade_average',
            field=models.FloatField(default=0.0),
        ),
    ]
