# Generated by Django 3.2.6 on 2021-11-07 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic', '0006_dquestion_home_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='dquestion',
            name='hits',
            field=models.PositiveIntegerField(default=0, verbose_name='조회수'),
        ),
    ]
