# Generated by Django 3.2.6 on 2021-08-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic', '0006_credit_grade_average'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='pass_fail',
            field=models.CharField(choices=[('O', 'O'), ('X', 'X')], max_length=20),
        ),
    ]
