# Generated by Django 3.2.6 on 2021-08-03 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domestic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nickname', models.CharField(max_length=20, verbose_name='닉네임')),
                ('user_email', models.EmailField(blank=True, max_length=254, verbose_name='이메일')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='domestic.domestic', verbose_name='소속 대학')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
