# Generated by Django 3.2.6 on 2021-08-05 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='university',
            field=models.CharField(blank=True, default=3, max_length=100, verbose_name='소속 대학'),
            preserve_default=False,
        ),
    ]
