# Generated by Django 3.2.6 on 2021-08-05 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_alter_user_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='university',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='소속 대학'),
        ),
    ]
