# Generated by Django 3.2.6 on 2021-08-03 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question', '0003_auto_20210803_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_author',
            field=models.ForeignKey(default='aa', on_delete=django.db.models.deletion.CASCADE, to='login.user'),
            preserve_default=False,
        ),
    ]
