# Generated by Django 3.2.6 on 2021-08-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foreign', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
