# Generated by Django 3.2.6 on 2021-08-04 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foreign', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='foreign',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='foreign.foreign'),
        ),
    ]
