# Generated by Django 3.2.6 on 2021-08-10 07:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foreign', '0003_auto_20210809_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='away_semester',
            field=models.CharField(choices=[('1학기', '1학기'), ('2학기', '2학기')], max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='away_year',
            field=models.IntegerField(default=2020, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)]),
        ),
    ]
