# Generated by Django 3.2.6 on 2021-08-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foreign', '0004_auto_20210810_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='review/%Y/%M/%d'),
        ),
    ]
