# Generated by Django 3.2.6 on 2021-08-12 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foreign', '0007_frecomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
