# Generated by Django 3.2.6 on 2021-08-14 08:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('foreign', '0008_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2021, 8, 14, 8, 53, 13, 441344, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
