# Generated by Django 3.2.6 on 2021-10-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foreign', '0009_auto_20210814_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreign',
            name='away_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
