# Generated by Django 3.2.6 on 2021-11-18 16:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foreign', '0011_auto_20211108_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='scrapers',
            field=models.ManyToManyField(blank=True, related_name='scraping', to=settings.AUTH_USER_MODEL),
        ),
    ]
